# Pre-processing for OSHA Accident Injury Data

In [1]:
%load_ext nb_black

In [2]:
import pandas as pd

In [3]:
osha_data_dictionary = pd.read_csv("./data/osha_data_dictionary.csv")
osha_accident_lookup = pd.read_csv("./data/osha_accident_lookup2 2.csv")
osha_accident_injury = pd.read_csv("./data/osha_accident_injury.csv")

In [ ]:
# 1. Degree of Injury predictor ~ Age, Height, Occupation, Sex

In [16]:
osha_accident_lookup["accident_code"].value_counts()

OCC     573
OPER     71
SO       48
BD       31
CAUS     30
IN       22
HU       20
EN       18
ENDU     17
FT       14
COST      7
PTYP      5
DEGR      3
TASK      2
Name: accident_code, dtype: int64

In [25]:
pd.set_option("display.max_colwidth", None)

In [26]:
osha_data_dictionary[osha_data_dictionary["table_name"] == "osha_accident_injury"]

,table_name,column_name,attribute_name,definition,column_datatype,display_name
20,osha_accident_injury,load_dt,Load Date Timestamp,The date the load was completed.,date,No Label
21,osha_accident_injury,degree_of_inj,Degree of Injury,1=Fatality. 2=Hospitalized injuries. 3=No Hospitalized injuries,"Numeric, Length=1",Degree of Injury
22,osha_accident_injury,task_assigned,Task Assigned,1=Task regularly assigned. 2=Task not regularly assigned,"Numeric, Length=1",Task Assigned
23,osha_accident_injury,age,Age,Age of the injured person,"Numeric, Length=2",Age
24,osha_accident_injury,fat_cause,Construction Cause of Fatality,Construction - cause of fatality (code table CAUS),"Numeric, Length=2",Cause of Fatality
25,osha_accident_injury,const_op_cause,Construction Cause of Injury,Construction - cause of injury (code table OPER),"Numeric, Length=2",Cause of Injury
26,osha_accident_injury,fall_distance,Distance of Fall,Construction - distance of fall (feet),"Numeric, Length=4",Distance of Fall
27,osha_accident_injury,fall_ht,Height of Person,Construction - height of person when fell (feet),"Numeric, Length=4",Height of Person
28,osha_accident_injury,const_op,Construction Operation Code,Construction - operation code (code table OPER),"Numeric, Length=2",Operation Code
29,osha_accident_injury,evn_factor,Environmental Factor,Environmental factor code - code table EN,"Numeric, Length=2",Environmental Factor
30,osha_accident_injury,event_type,Event Type,Event type code - code table FT,"Numeric, Length=2",Event Type
31,osha_accident_injury,hazsub,Hazardous Substance,Hazardous substance code,"Alphanumeric, Length=4",Hazardous Substance
32,osha_accident_injury,hum_factor,Human Factor,Human factor code - code table HU,"Numeric, Length=2",Human Factor
33,osha_accident_injury,summary_nr,Summary NR,Identifies the accident OSHA-170 form,"Numeric, Length=9",Summary NR
34,osha_accident_injury,rel_insp_nr,Related Inspection NR,Identifies the inspection associated with investigating a particular injury,"Numeric, Length=9",Related Inspection NR
35,osha_accident_injury,injury_line_nr,Injury Line Number,Injury line number - is often referenced in the abstract text to refer to a particular person.,"Numeric, Length=3",Injury Line Number
36,osha_accident_injury,sex,Sex,M=Male. F=Female,"Alphanumeric, Length=1",Sex
37,osha_accident_injury,nature_of_inj,Nature of Injury,Nature of injury code - code table IN,"Numeric, Length=2",Nature of Injury
38,osha_accident_injury,occ_code,Occupation Code,Occupation code - code table OCC,"Numeric, Length=3",Occupation Code
39,osha_accident_injury,part_of_body,Part of Body,Part of body code - code table BD,"Numeric, Length=2",Part of Body
40,osha_accident_injury,src_of_injury,Source of Injury,Source of injury code - code table SO,"Numeric, Length=2",Source of Injury

In [36]:
osha_data_dictionary[osha_data_dictionary["table_name"] == "osha_accident_injury"][
    ["column_name", "definition"]
][
    osha_data_dictionary[osha_data_dictionary["table_name"] == "osha_accident_injury"][
        "definition"
    ].str.contains("code table")
].apply(
    lambda row: (
        row["column_name"],
        row["definition"].replace("(", "").replace(")", "").split(" ")[-1],
    ),
    axis=1,
    result_type="broadcast",
)

       column_name definition
24       fat_cause       CAUS
25  const_op_cause       OPER
28        const_op       OPER
29      evn_factor         EN
30      event_type         FT
32      hum_factor         HU
37   nature_of_inj         IN
38        occ_code        OCC
39    part_of_body         BD
40   src_of_injury         SO

In [37]:
osha_accident_lookup

,accident_code,accident_number,accident_value,accident_letter,load_date
0,OCC,757.0,"Separating, filtering & clarifying mach. operators",NaN,2018-11-09 20:56:02 EST
1,OCC,758.0,Compressing and compacting machine operators,NaN,2018-11-09 20:56:02 EST
2,OCC,759.0,Painting and paint spraying machine operators,NaN,2018-11-09 20:56:02 EST
3,OCC,763.0,"Roasting and baking machine operators, food",NaN,2018-11-09 20:56:02 EST
4,OCC,764.0,"Washing, cleaning and pickling machine operators",NaN,2018-11-09 20:56:02 EST
...,...,...,...,...,...
856,OCC,749.0,Miscellaneous textile machine operators,NaN,2018-11-09 20:56:02 EST
857,OCC,753.0,Cementing and gluing machine operators,NaN,2018-11-09 20:56:02 EST
858,OCC,754.0,Packaging and filling machine operators,NaN,2018-11-09 20:56:02 EST
859,OCC,755.0,Extruding and forming machine operators,NaN,2018-11-09 20:56:02 EST
860,OCC,756.0,Mixing and blending machine operators,NaN,2018-11-09 20:56:02 EST

In [12]:
osha_accident_injury[
    (osha_accident_injury["age"] > 0)
]

,summary_nr,rel_insp_nr,age,sex,nature_of_inj,part_of_body,src_of_injury,event_type,evn_factor,hum_factor,...,degree_of_inj,task_assigned,hazsub,const_op,const_op_cause,fat_cause,fall_distance,fall_ht,injury_line_nr,load_dt
31570,501015,107301277,33,M,12.0,20.0,26.0,2.0,4.0,4.0,...,1.0,2.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:38 EDT
31571,508580,18169789,30,M,2.0,28.0,41.0,12.0,11.0,9.0,...,1.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:38 EDT
31572,508598,107296972,22,M,21.0,4.0,41.0,14.0,18.0,14.0,...,1.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:38 EDT
31573,508820,18167858,36,M,21.0,5.0,24.0,1.0,6.0,1.0,...,1.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:38 EDT
31574,508895,301494217,47,M,2.0,28.0,41.0,12.0,18.0,1.0,...,1.0,2.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:38 EDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203468,902060359,314698606,29,M,1.0,10.0,26.0,2.0,4.0,10.0,...,2.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:41 EDT
203469,903050607,302017603,54,M,1.0,2.0,26.0,2.0,4.0,1.0,...,2.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:41 EDT
203470,903077535,304440381,39,M,10.0,12.0,15.0,13.0,13.0,1.0,...,2.0,1.0,8880,25.0,29.0,11.0,NaN,NaN,1,2019-07-22 00:18:41 EDT
203471,903080125,304230857,25,M,5.0,12.0,16.0,14.0,12.0,1.0,...,3.0,1.0,8880,24.0,24.0,23.0,NaN,NaN,1,2019-07-22 00:18:41 EDT
203473,980213516,101356459,24,M,12.0,4.0,42.0,5.0,13.0,20.0,...,1.0,1.0,NaN,0.0,0.0,0.0,NaN,NaN,1,2019-07-22 00:18:41 EDT

In [4]:
# create list of all distinct accident codes
code_list = []
for index in osha_accident_lookup.index:
    if osha_accident_lookup["accident_code"][index] not in code_list:
        code_list.append(osha_accident_lookup["accident_code"][index])

# remove values not found in actual data
code_list.remove("PTYP")
code_list.remove("COST")
code_list.remove("ENDU")

# create list of dictionaries, s.t. each item maps accident number to accident value
# there is a unique map for each unique accident code
mapList = []
for code in code_list:
    temp_df = pd.DataFrame(
        osha_accident_lookup[osha_accident_lookup["accident_code"] == code]
    )
    temp_map = dict(zip(temp_df["accident_number"], temp_df["accident_value"]))
    mapList.append(temp_map)

# create dictionary that maps code from osha_accident_lookup to column name in osha_accident_injury.csv
code_to_column = dict(
    {
        "OCC": "occ_code",
        "CAUS": "fat_cause",
        "DEGR": "degree_of_inj",
        "OPER": "const_op_cause",
        "EN": "evn_factor",
        "FT": "event_type",
        "HU": "hum_factor",
        "IN": "nature_of_inj",
        "BD": "part_of_body",
        "SO": "src_of_injury",
        "TASK": "task_assigned",
    }
)

# replace numbers in injury data with string values of what the #'s represent
iterator = 0
for item in mapList:
    code = code_list[iterator]
    col_name = code_to_column[code]
    osha_accident_injury[col_name] = osha_accident_injury[col_name].map(item)
    iterator += 1

osha_accident_injury["const_op"] = osha_accident_injury["const_op"].map(mapList[1])

osha_accident_injury.head()

,summary_nr,rel_insp_nr,age,sex,nature_of_inj,part_of_body,src_of_injury,event_type,evn_factor,hum_factor,...,degree_of_inj,task_assigned,hazsub,const_op,const_op_cause,fat_cause,fall_distance,fall_ht,injury_line_nr,load_dt
0,18,10006732,0,NaN,Electric Shock,HAND(S),ELEC APPARAT/WIRING,SHOCK,OTHER,"MISJUDGMENT, HAZ. SITUATION",...,Fatality,Task regularly assigned,NaN,NaN,NaN,NaN,NaN,NaN,1,2017-03-20 01:00:11 EDT
1,26,159996,0,NaN,Other,MULTIPLE,WORKING SURFACE,FALL(FROM ELEVATION),WORK-SURFACE/FACIL-LAYOUT COND,SAFETY DEVICES REMOVED/INOPER.,...,Fatality,Task regularly assigned,NaN,NaN,NaN,NaN,NaN,NaN,1,2017-03-20 01:00:11 EDT
2,34,10013225,0,NaN,Other,BODYSYSTEM,GASES,INHALATION,OTHER,"MISJUDGMENT, HAZ. SITUATION",...,Fatality,Task regularly assigned,0270,NaN,NaN,NaN,NaN,NaN,1,2017-03-20 01:00:11 EDT
3,42,10014439,0,NaN,Amputation,FINGER(S),HOISTING APPARATUS,CAUGHT IN OR BETWEEN,SHEAR POINT ACTION,"MISJUDGMENT, HAZ. SITUATION",...,Hospitalized injury,Task not regularly assigned,NaN,NaN,NaN,NaN,NaN,NaN,1,2017-03-20 01:00:11 EDT
4,59,19523588,0,NaN,Burn/Scald(Heat),BODYSYSTEM,FIRE/SMOKE,ABSORPTION,CHEMICAL ACTION/REACTION EXPOS,"MISJUDGMENT, HAZ. SITUATION",...,Hospitalized injury,Task regularly assigned,NaN,NaN,NaN,NaN,NaN,NaN,1,2017-03-20 01:00:11 EDT

In [5]:
pd.set_option("display.max_columns", None)

In [6]:
osha_accident_injury.isna().mean()

summary_nr        0.000000
rel_insp_nr       0.000000
age               0.000000
sex               0.344250
nature_of_inj     0.180308
part_of_body      0.180308
src_of_injury     0.180308
event_type        0.027124
evn_factor        0.180677
hum_factor        0.180770
occ_code          0.018174
degree_of_inj     0.027119
task_assigned     0.037228
hazsub            0.856065
const_op          0.919199
const_op_cause    0.847632
fat_cause         0.877537
fall_distance     0.988298
fall_ht           0.934611
injury_line_nr    0.000000
load_dt           0.000000
dtype: float64

In [12]:
osha_accident_injury.drop(
    [
        "hazsub",
        "const_op",
        "const_op_cause",
        "fat_cause",
        "fall_distance",
        "fall_ht",
        *["summary_nr", "rel_insp_nr", "injury_line_nr", "load_dt"],
    ],
    axis=1,
).dropna().to_csv("./data/processed.csv")

In [16]:
osha_accident_injury.drop(
    [
        "hazsub",
        "fat_cause",
        "fall_distance",
        "fall_ht",
        *["summary_nr", "rel_insp_nr", "injury_line_nr", "load_dt"],
    ],
    axis=1,
).dropna().to_csv("./data/processed_with_const_op.csv")